// Banner Action Types
export const GET_BANNER_START = "GET_BANNER_START";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILED = "GET_BANNER_FAILED";

//Category Action Types
export const GET_CATEGORY_START = "GET_CATEGORY_START";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

// Product Action Types
export const GET_PRODUCT_LIST_START = "GET_PRODUCT_LIST_START";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";

// Cart Action Types
export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";
export const TOTAL_CART_COUNT = "TOTAL_CART_COUNT";
